- hosts: localhost
  tasks:
    - name: add undercloud to inventry
      add_host:
        name: "undercloud"
        ansible_host: "172.16.0.2"
        
- hosts: undercloud
  become: yes
  become_user: stack
  tasks:
    - name: copy the browbeat vars file
      copy:
        src: browbeat_vars.yml
        dest: /home/stack/browbeat/ansible/install/group_vars/all.yml

    - name: install browbeat
      shell: ansible-playbook -i hosts install/browbeat.yml
      args:
        chdir: /home/stack/browbeat/ansible
