- hosts: 127.0.0.1
  vars_files:
    - browbeat-workload-vars.yml
    - browbeat-config-vars.yml
  tasks:
    - name: Creating config with respected dfg
      template:
        src: browbeat-config-template.yaml.j2
        dest: browbeat-config.yaml
